# -*- coding: utf-8 -*-
"""plot assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ORpJ30Medj1-xbgk8mIPwiRbMJ1aRZc6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/finalCleanedData.csv')

df.head()

df.describe()

df.plot.bar()

import matplotlib.pyplot as plt
plt.style.use('ggplot')
df.plot.bar(x='vote_average',y='profit')

"""yes high vote average made a profit"""

import matplotlib.pyplot as plt
plt.style.use('ggplot')
df.plot.bar('revenue')

df.info()

import matplotlib.pyplot as plt
plt.style.use('ggplot')
df.plot.scatter(x='Producer1',y='profit')

pip install pandas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/finalCleanedData.csv')

df.head()

df.describe()

df.info()

df.plot.scatter(x='runtime',y='profit',c='red',s=50,figsize=(12,3))

df.plot(x='Producer1', y='Producer2', style='o').astype(float)
plt.title('Producer1 vs Producer2')
plt.xlabel('Producer1')
plt.ylabel('Producer2')
plt.show()
df[['Producer1','Producer2']].corr()

df.plot.scatter(x = 'Producer1',y = 'Producer2')

df.plot.scatter(x = 'Producer1',y = 'Producer2',c = 'profit',cmap='viridis')

df.plot.scatter(x = 'TotalLanguages',y = 'profit')

df.plot.scatter(x = 'vote_average',y = 'profit')

data=pd.read_csv('/content/finalCleanedData.csv')

